In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
X, y = load_iris(return_X_y=True)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
import numpy as np

(X_train - np.mean(X_train, axis=0)) / np.std(X_train, axis=0)

array([[ 0.62703432,  0.83124476,  1.06772411,  1.58811807],
       [ 1.14417602, -1.23253533,  1.18404449,  0.78962295],
       [-1.18296165,  0.14331806, -1.31684358, -1.47277989],
       [-1.95867421, -0.08599084, -1.54948433, -1.47277989],
       [ 0.36846347, -0.54460863,  0.54428242, -0.00887217],
       [-0.14867824, -0.31529974,  0.25348148,  0.12421035],
       [ 0.62703432, -0.31529974,  1.06772411,  0.78962295],
       [ 0.62703432, -1.69115313,  0.36980186,  0.12421035],
       [-1.57081793,  0.14331806, -1.31684358, -1.33969737],
       [-0.9243908 ,  1.74848035, -1.2586834 , -1.33969737],
       [ 0.36846347, -0.08599084,  0.6606028 ,  0.78962295],
       [ 1.0148906 , -0.31529974,  0.48612224,  0.12421035],
       [ 1.14417602, -0.08599084,  0.83508336,  1.45503555],
       [ 1.79060316,  0.37262696,  1.30036486,  0.78962295],
       [-0.14867824, -0.54460863,  0.42796205,  0.12421035],
       [-0.14867824, -1.00322643, -0.15363983, -0.27503721],
       [ 0.49774889, -0.

In [13]:
X_train_scaled

array([[ 0.62703432,  0.83124476,  1.06772411,  1.58811807],
       [ 1.14417602, -1.23253533,  1.18404449,  0.78962295],
       [-1.18296165,  0.14331806, -1.31684358, -1.47277989],
       [-1.95867421, -0.08599084, -1.54948433, -1.47277989],
       [ 0.36846347, -0.54460863,  0.54428242, -0.00887217],
       [-0.14867824, -0.31529974,  0.25348148,  0.12421035],
       [ 0.62703432, -0.31529974,  1.06772411,  0.78962295],
       [ 0.62703432, -1.69115313,  0.36980186,  0.12421035],
       [-1.57081793,  0.14331806, -1.31684358, -1.33969737],
       [-0.9243908 ,  1.74848035, -1.2586834 , -1.33969737],
       [ 0.36846347, -0.08599084,  0.6606028 ,  0.78962295],
       [ 1.0148906 , -0.31529974,  0.48612224,  0.12421035],
       [ 1.14417602, -0.08599084,  0.83508336,  1.45503555],
       [ 1.79060316,  0.37262696,  1.30036486,  0.78962295],
       [-0.14867824, -0.54460863,  0.42796205,  0.12421035],
       [-0.14867824, -1.00322643, -0.15363983, -0.27503721],
       [ 0.49774889, -0.

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
X_min = np.min(X_train, axis=0)
X_max = np.max(X_test, axis=0)

(X_train - X_min) / (X_max - X_min)

array([[0.55555556, 0.7       , 0.80701754, 0.95833333],
       [0.66666667, 0.25      , 0.84210526, 0.70833333],
       [0.16666667, 0.55      , 0.0877193 , 0.        ],
       [0.        , 0.5       , 0.01754386, 0.        ],
       [0.5       , 0.4       , 0.64912281, 0.45833333],
       [0.38888889, 0.45      , 0.56140351, 0.5       ],
       [0.55555556, 0.45      , 0.80701754, 0.70833333],
       [0.55555556, 0.15      , 0.59649123, 0.5       ],
       [0.08333333, 0.55      , 0.0877193 , 0.04166667],
       [0.22222222, 0.9       , 0.10526316, 0.04166667],
       [0.5       , 0.5       , 0.68421053, 0.70833333],
       [0.63888889, 0.45      , 0.63157895, 0.5       ],
       [0.66666667, 0.5       , 0.73684211, 0.91666667],
       [0.80555556, 0.6       , 0.87719298, 0.70833333],
       [0.38888889, 0.4       , 0.61403509, 0.5       ],
       [0.38888889, 0.3       , 0.43859649, 0.375     ],
       [0.52777778, 0.4       , 0.66666667, 0.70833333],
       [0.33333333, 0.15      ,